# Generated by Django 3.0.5 on 2023-06-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0007_auto_20200325_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='face_id',
            field=models.IntegerField(null=True),
        ),
    ]
